import type { NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";
import { Navbar } from "./../components/Navbar";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>QR Code Gen</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
      </main>
    </>
  );
};

export default Home;
